### ISSUE TITLE
Question: What is the difference between your's and quasar rat itself

### ISSUE THREAD

**Issue by Taki7o7** [wearelegal/CinaRAT#1]
check title

**Comment by wearelegal** [comment]
Hi!
Now we have not important differences between both rats, the only one, is that Quasar seems discontinued, and soon we'll have AV bypass, and some little bugs from Quasar fixeds, and other features like the multilanguage, SDK, and a modular system to implement "plugins". I have some problemas to continue programming that, but we'll do it. I know that the CinaRAT looks equal Quasar, and I understand your question, but to have good changes, we need a little help from the community, and time. I expect have solved your question. Have a good day Taki7o7!
